version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_database
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - storage
  storage:
    image: storage
    container_name: storage
    environment:
      - POSTGRES_ADDR=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DB=leaks
    ports:
      - '30001:30001'
    depends_on:
      - postgres
    networks:
      - storage
networks:
  storage: {}